### ISSUE TITLE
Cloud Task depends on App Engine Application

### ISSUE THREAD

**Issue by Zhong-z** [mattes/google_cloud_run#1]
Hi @mattes 

First of all thanks for the great gem. The integration helps a lot. 

I have read the Cloud Task Consideration section in the Readme, and I'm wondering how do you deal with Cloud Tasks depends on having an App Engine application?

I think I can create a dummy application to setup the queues, but not sure if this is best practice.

**Comment by mattes** [comment]
I'm glad it helps you. 

That is correct, Cloud Tasks currently depend on App Engine. It was confusing for me, too. I followed the docs and just ended up with a working App Engine setup. No App Engine app is ever run. You just have to go through the initial setup steps. Hope it helps.

> To set up your Cloud environment, create a GCP project and add an App Engine application with billing enabled. You must have an App Engine application in your project to run your queue. 
https://cloud.google.com/tasks/docs/quickstart#before-you-begin
